# @format

steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/task-app-backend:$COMMIT_SHA',
        './backend',
      ]

  # Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA',
        './frontend',
      ]

  # Push the backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/task-app-backend:$COMMIT_SHA']

  # Push the frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'task-app-backend'
      - '--image=gcr.io/$PROJECT_ID/task-app-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=8000'
      - '--set-env-vars=DATABASE_URL=sqlite:///./data/tasks.db,ENVIRONMENT=production'

  # Get the URL of the backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe task-app-backend --platform managed --region us-central1 --format="value(status.url)")
        echo "REACT_APP_API_URL=$${BACKEND_URL}" > frontend/.env.production

  # Rebuild the frontend image with the backend URL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA',
        './frontend',
      ]

  # Push the updated frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'task-app-frontend'
      - '--image=gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/task-app-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/task-app-frontend:$COMMIT_SHA'

# Set timeout for the build (default is 10 minutes)
timeout: '1800s'
